# 1.2.1 Пример 

In [3]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [4]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2 Пример

In [7]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, b, c, d, sep='\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 11 12 13 14 15 16 17 18 19]


# 1.2.3 Пример

In [12]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.008449081425746852 0.9938940890246899 0.5293054074004776
[[0.98484183 0.6080576  0.5946662  0.84613442 0.66632968 0.0475258
  0.41399686 0.98639582 0.79205306 0.72851964]
 [0.20697229 0.82169265 0.16089396 0.27674008 0.72516212 0.18761176
  0.74894305 0.20697633 0.91389687 0.32357395]
 [0.83366413 0.07156842 0.64607812 0.71716601 0.09556274 0.1446181
  0.09935564 0.77848954 0.50800192 0.8841369 ]
 [0.64548786 0.49552497 0.14091784 0.81130846 0.56114995 0.97048097
  0.74277795 0.13213038 0.76838345 0.28254728]
 [0.59768843 0.89581636 0.87076024 0.3524984  0.68364188 0.13765293
  0.78801573 0.96737102 0.85784546 0.66152543]
 [0.36518414 0.92306975 0.27774031 0.57988744 0.61214025 0.80750358
  0.82239145 0.09060049 0.12701022 0.46765901]
 [0.79203831 0.09512435 0.00844908 0.07088747 0.825492   0.56064027
  0.23397799 0.27062616 0.67595004 0.06232726]
 [0.36108181 0.99389409 0.52829577 0.5363188  0.16381691 0.6132046
  0.20005801 0.14096441 0.78755    0.65593749]
 [0.71595216 0.5558979  

# 1.2.4 Пример

In [25]:
A = np.arange(25).reshape(5, 5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

In [28]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 1.2.6 Пример

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

In [5]:
A = np.zeros((8, 8), dtype=int)
A[::2, ::2] = 1
A[1::2, 1::2] = 1
print(A)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 1.3.2 Задание

In [6]:
A = np.arange(25).reshape(5, 5) % 5
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание

In [7]:
A = np.random.random((3, 3, 3))
print(A)

[[[0.88125992 0.48666513 0.24531069]
  [0.4186471  0.51509063 0.58043194]
  [0.24254052 0.48517626 0.98928497]]

 [[0.38846046 0.8458812  0.0415857 ]
  [0.20758552 0.62362326 0.97458605]
  [0.75800046 0.82028081 0.07715348]]

 [[0.25662844 0.31951939 0.26086967]
  [0.52675533 0.45374839 0.23478568]
  [0.03831801 0.17070732 0.84166537]]]


# 1.3.4 Задание

In [8]:
A = np.ones((5, 5), dtype=int)
A[1:-1:, 1:-1:] = 0
print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# 1.3.5 Задание

In [9]:
A = np.arange(20)
A[::-1].sort()
print(A)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


# 1.3.6 Задание

In [67]:
A = np.arange(24).reshape(4, 3, 2)
print(A.shape, A.size, A.ndim)

(4, 3, 2) 24 3


# 2.2.1 Пример

In [10]:
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1, s2, s3, sep='\n')

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


# 2.2.2 Пример

In [11]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# 2.2.3 Пример

In [12]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

In [5]:
url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример

In [32]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 2.2.6 Пример

In [35]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

In [39]:
dataframe[dataframe["PClass"] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

In [10]:
a = pd.Series([2, 4, 8, 16])
b = pd.Series([1, 3, 9, 12])
print(a, b, sep='\n')
print("Distance:", sum((a - b)**2)**0.5)

0     2
1     4
2     8
3    16
dtype: int64
0     1
1     3
2     9
3    12
dtype: int64
Distance: 4.358898943540674


# 2.3.2 Задание

In [11]:
url = "https://raw.githubusercontent.com/akmand/datasets/main/bank_marketing.csv"
df = pd.read_csv(url)
df

V1            V2        V3         V4  V5    V6   V7   V8         V9  \
0      58    management   married   tertiary  no  2143  yes   no    unknown   
1      44    technician    single  secondary  no    29  yes   no    unknown   
2      33  entrepreneur   married  secondary  no     2  yes  yes    unknown   
3      47   blue-collar   married    unknown  no  1506  yes   no    unknown   
4      33       unknown    single    unknown  no     1   no   no    unknown   
...    ..           ...       ...        ...  ..   ...  ...  ...        ...   
45206  51    technician   married   tertiary  no   825   no   no   cellular   
45207  71       retired  divorced    primary  no  1729   no   no   cellular   
45208  72       retired   married  secondary  no  5715   no   no   cellular   
45209  57   blue-collar   married  secondary  no   668   no   no  telephone   
45210  37  entrepreneur   married  secondary  no  2971   no   no   cellular   

       V10  V11   V12  V13  V14  V15      V16  Class  
0        5  may   261    1   -1    0  unknown      1  
1        5  may   151    1   -1    0  unknown      1  
2        5  may    76    1   -1    0  unknown      1  
3        5  may    92    1   -1    0  unknown      1  
4        5  may   198    1   -1    0  unknown      1  
...    ...  ...   ...  ...  ...  ...      ...    ...  
45206   17  nov   977    3   -1    0  unknown      2  
45207   17  nov   456    2   -1    0  unknown      2  
45208   17  nov  1127    5  184    3  success      2  
45209   17  nov   508    4   -1    0  unknown      1  
45210   17  nov   361    2  188   11    other      1  

[45211 rows x 17 columns]

# 2.3.3 Задание

In [8]:
df.head(2)
df.tail(3)
df.shape
df.describe()
df.iloc[1:4]
df[df["V3"] == "single"].head(2)

V1          V2      V3         V4  V5  V6   V7  V8       V9  V10  V11  V12  \
1  44  technician  single  secondary  no  29  yes  no  unknown    5  may  151   
4  33     unknown  single    unknown  no   1   no  no  unknown    5  may  198   

   V13  V14  V15      V16  Class  
1    1   -1    0  unknown      1  
4    1   -1    0  unknown      1

# 3.2.1 Пример

In [92]:
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2 Пример

In [4]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print(standardized)

print("Среднее;", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее; 0
Стандартное отклонение: 1.0


# 3.2.3 Пример

In [13]:
scaler = preprocessing.MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})
dfTest
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

# 3.3.2 Задание

In [9]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)

scalerM = MinMaxScaler()
dataframe[['sepal_length_cm']] = scalerM.fit_transform(dataframe[['sepal_length_cm']])

scalerZ = StandardScaler()
dataframe[['sepal_width_cm']] = scalerZ.fit_transform(dataframe[['sepal_width_cm']])

dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]