In [91]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

# 1.2.1 Пример 

In [4]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[:, 1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[ 2  4  6  8 10]


# 1.2.2 Пример

In [5]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, b, c, d, sep='\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 11 12 13 14 15 16 17 18 19]


# 1.2.3 Пример

In [6]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.003698422641839949 0.988099151593568 0.46551760544676357


# 1.2.4 Пример

In [8]:
A = np.arange(25).reshape(5, 5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

In [9]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 1.2.6 Пример

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

In [17]:
A = np.zeros((8, 8), dtype=int)
A[1::2, 1::2] = 1
A[::2, ::2] = 1
print(A)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 1.3.2 Задание

In [27]:
A = np.arange(25).reshape(5, 5) % 5
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание

In [29]:
A = np.random.random((3, 3, 3))
print(A)

[[[0.7369118  0.85556073 0.06672791]
  [0.24559855 0.12114228 0.91049981]
  [0.24356566 0.17758326 0.84439923]]

 [[0.13294899 0.2407808  0.22129498]
  [0.70119899 0.7701048  0.34678328]
  [0.72362764 0.17137298 0.54407796]]

 [[0.90352602 0.22203975 0.10229251]
  [0.97375833 0.51423778 0.79587331]
  [0.87490027 0.77815714 0.30032417]]]


# 1.3.4 Задание

In [32]:
A = np.ones((5, 5), dtype=int)
A[1:-1:, 1:-1:] = 0
print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# 1.3.5 Задание

In [37]:
A = np.arange(20)
A[::-1].sort()
print(A)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


# 1.3.6 Задание

In [44]:
A = np.arange(24).reshape(4, 3, 2)
print(A.shape, A.size, A.ndim)

(4, 3, 2) 24 3


# 2.2.1 Пример

In [53]:
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1, s2, s3, sep='\n')

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


# 2.2.2 Пример

In [54]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# 2.2.3 Пример

In [56]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

In [57]:
url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример

In [61]:
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1
                  Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0
(1313, 6)
              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000


# 2.2.6 Пример

In [62]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

In [63]:
dataframe[dataframe["PClass"] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

In [71]:
a = pd.Series([2, 4, 3, -10])
b = pd.Series([-2, 1, 6, 1])
print(a, b, sep='\n')
print("Distance:", sum((a - b)**2)**0.5)

0     2
1     4
2     3
3   -10
dtype: int64
0   -2
1    1
2    6
3    1
dtype: int64
Distance: 12.449899597988733


# 2.3.2 Задание

In [74]:
url = "https://raw.githubusercontent.com/akmand/datasets/main/anneal.csv"
df = pd.read_csv(url)

family product-type steel  carbon  hardness temper_rolling condition  \
0      ?            C     A       8         0              ?         S   
1      ?            C     R       0         0              ?         S   
2      ?            C     R       0         0              ?         S   
3      ?            C     A       0        60              T         ?   
4      ?            C     A       0        60              T         ?   

  formability  strength non-ageing  ...  s  p  shape  thick   width  len oil  \
0           ?         0          ?  ...  ?  ?   COIL  0.700   610.0    0   ?   
1           2         0          ?  ...  ?  ?   COIL  3.200   610.0    0   ?   
2           2         0          ?  ...  ?  ?  SHEET  0.700  1300.0  762   ?   
3           ?         0          ?  ...  ?  ?   COIL  2.801   385.1    0   ?   
4           ?         0          ?  ...  ?  ?  SHEET  0.801   255.0  269   ?   

  bore packing class  
0    0       ?     3  
1    0       ?     3  
2    0       ?     3  
3    0       ?     3  
4    0       ?     3  

[5 rows x 39 columns]

# 2.3.3 Задание

In [78]:
print(df.head(2))
print(df.tail(3))
print(df.shape)
print(df.describe())
print(df.iloc[1:4])
df[df["shape"] == 'COIL'].head(2)

  family product-type steel  carbon  hardness temper_rolling condition  \
0      ?            C     A       8         0              ?         S   
1      ?            C     R       0         0              ?         S   

  formability  strength non-ageing  ...  s  p shape thick  width len oil bore  \
0           ?         0          ?  ...  ?  ?  COIL   0.7  610.0   0   ?    0   
1           2         0          ?  ...  ?  ?  COIL   3.2  610.0   0   ?    0   

  packing class  
0       ?     3  
1       ?     3  

[2 rows x 39 columns]
    family product-type steel  carbon  hardness temper_rolling condition  \
895      ?            C     V       0         0              ?         S   
896      ?            C     A       0        85              T         ?   
897      ?            C     A       0        85              T         ?   

    formability  strength non-ageing  ...  s  p  shape  thick  width  len oil  \
895           2         0          ?  ...  ?  ?  SHEET  1.599  150.0  

family product-type steel  carbon  hardness temper_rolling condition  \
0      ?            C     A       8         0              ?         S   
1      ?            C     R       0         0              ?         S   

  formability  strength non-ageing  ...  s  p shape thick  width len oil bore  \
0           ?         0          ?  ...  ?  ?  COIL   0.7  610.0   0   ?    0   
1           2         0          ?  ...  ?  ?  COIL   3.2  610.0   0   ?    0   

  packing class  
0       ?     3  
1       ?     3  

[2 rows x 39 columns]

# 3.2.1 Пример

In [92]:
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2 Пример

In [95]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print(standardized)

print("Среднее;", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее; 0
Стандартное отклонение: 1.0


# 3.2.3 Пример

In [ ]:
scaler = preprocessing.MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest