# Импорты

In [11]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# 1.1. Библиотека NumPy
## 1.2.1. Пример
Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с 0. 

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2. Пример
Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать веткор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [ ]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, '\n', b, '\n', c, '\n', d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


# 1.2.3. Пример
Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [ ]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.00982775546095227 0.9580188737117802 0.4965735408460334


## 1.2.4. Пример
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [ ]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 1.2.5. Пример
Выяснить результат следующих выражений: <br>
0 * np.nan <br>
np.nan == np.nan <br>
np.inf > np.nan <br>
np.nan - np.nan <br>
0.3 == 3 * 0.1 <br>

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 1.2.6. Пример
Отсортировать массив.

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1. Задание!!!
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [13]:
a = np.zeros(64).reshape(8,8)
# for i in range(8):
#     for j in range(8):
#         if (j+i)%2==0:
#             a[i,j] = 1
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## 1.3.2. Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange.

In [3]:
Z = np.arange(25).reshape(5,5)
for i in range(5):
    Z[i] = np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 1.3.3. Задание
Создать массив 3x3x3 со случайными значениями.

In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.66494573 0.57248285 0.27058635]
  [0.56241648 0.06758935 0.31503138]
  [0.42283231 0.15487382 0.35927842]]

 [[0.98439494 0.39366546 0.67695252]
  [0.91124334 0.04994828 0.43466286]
  [0.97480537 0.39519196 0.69931229]]

 [[0.51453937 0.09057561 0.79182047]
  [0.04616691 0.36333237 0.84927437]
  [0.44292535 0.37638422 0.5788423 ]]]


## 1.3.4. Задание
Создать матрицу с 0 внутри и 1 на границах.

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 1.3.5. Задание
Создайте массив и отсортируйте его по убыванию.

In [4]:
Z = np.random.random(25)
Z = np.sort(Z, axis=None)[::-1].reshape(5,5)
print(Z)

[[0.96864588 0.94063546 0.93958983 0.92093388 0.85568122]
 [0.85489464 0.82590231 0.79801415 0.71877364 0.71262136]
 [0.70475933 0.67970889 0.64742392 0.58860033 0.55906151]
 [0.46104302 0.32979081 0.28864297 0.27199248 0.23920623]
 [0.19025509 0.14152435 0.03337586 0.03323139 0.01857083]]


## 1.3.6. Задание
Создайте матрицу, выведите её форму, размер и размерность.

In [6]:
Z = np.random.random(25).reshape(5,5)
print(Z)
for i in Z:
    i *= 10
size = np.size(Z)
dim = np.ndim(Z)
shape = np.shape(Z)
print(shape,size,dim)

[[0.23146811 0.93480569 0.50597328 0.217604   0.38550233]
 [0.2282069  0.9593822  0.17038201 0.38627334 0.22258647]
 [0.48079376 0.35949673 0.83133004 0.09991303 0.67853883]
 [0.2240667  0.7306969  0.07968004 0.75244499 0.42303343]
 [0.35838683 0.38644017 0.52494638 0.71978198 0.37715215]]
(5, 5) 25 2


# 2.1. Библиотека Pandas
## 2.2.1. Пример
Создать Series из списка Python, словаря Python и массива Numpy (установить буквенные метки для последнего).

In [ ]:
lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


## 2.2.2. Пример
Дано два Series. Напечатать их первые элементы и все элменты после третьего (во втором фрейме).

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


## 2.2.3. Пример
Создайте новый фрейм данных.

In [ ]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

## 2.2.4. Пример
Загрузите фрейм данных по ссылке: https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [ ]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

## 2.2.5. Пример
Проанализировать характеристики фрейма данных.

Одна из самых простых вещей, которые мы можем сделать после
загрузки данных, – это взглянуть на первые несколько строк с помощью
метода head. На последние строки можно посмотреть с помощью
функции tail. Мы также можем взглянуть на количество строк и
столбцов: dataframe.shape. Кроме того, используя метод describe, мы
можем получить описательную статистику для любых числовых
столбцов.
Более подробно с возможностями работы с фреймами данных
можно узнать по ссылке ниже:
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [ ]:
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [ ]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [ ]:
dataframe.shape

(1313, 6)

In [ ]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

## 2.2.6. Пример
Выберите индивидуальные данные или срезы фрейма данных.

In [ ]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

## 2.2.7. Пример
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [ ]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

## 2.3.1. Задание
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [7]:
a = pd.Series([2, 4, 6, 8])
b = pd.Series([2, 7, 6, 8])
print(sum((a - b)**2)**.5)

3.0


## 2.3.2. Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/5ceb3d288246704d42aba5f8e3a2864df73a3424/cdc_sample.csv'
dataframe = pd.read_csv(url)
print(dataframe.head(5))
print(dataframe.tail(2))
print(dataframe.shape)
print(dataframe.describe())
print(dataframe.iloc[5:7])
print(dataframe[dataframe['age'] == 28].head(3))

   exerany  hlthplan  smoke100  height  weight  wtdesire  age gender  \
0        1         1         1      75     265       225   45      m   
1        1         1         0      72     150       150   24      m   
2        1         1         1      69     137       150   47      m   
3        1         1         1      66     159       125   26      f   
4        1         1         0      63     145       125   33      f   

     genhlth  
0  very good  
1  excellent  
2  excellent  
3       good  
4  very good  
    exerany  hlthplan  smoke100  height  weight  wtdesire  age gender  \
58        1         1         0      73     175       190   28      m   
59        1         1         0      69     165       165   40      m   

      genhlth  
58  excellent  
59  very good  
(60, 9)
         exerany   hlthplan   smoke100     height      weight    wtdesire  \
count  60.000000  60.000000  60.000000  60.000000   60.000000   60.000000   
mean    0.750000   0.833333   0.516667  67.1833

## 2.3.3. Задание
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/5ceb3d288246704d42aba5f8e3a2864df73a3424/cdc_sample.csv'
dataframe = pd.read_csv(url)
print(dataframe.head(5))
print(dataframe.tail(2))
print(dataframe.shape)
print(dataframe.describe())
print(dataframe.iloc[5:7])
print(dataframe[dataframe['age'] == 28].head(3))

   exerany  hlthplan  smoke100  height  weight  wtdesire  age gender  \
0        1         1         1      75     265       225   45      m   
1        1         1         0      72     150       150   24      m   
2        1         1         1      69     137       150   47      m   
3        1         1         1      66     159       125   26      f   
4        1         1         0      63     145       125   33      f   

     genhlth  
0  very good  
1  excellent  
2  excellent  
3       good  
4  very good  
    exerany  hlthplan  smoke100  height  weight  wtdesire  age gender  \
58        1         1         0      73     175       190   28      m   
59        1         1         0      69     165       165   40      m   

      genhlth  
58  excellent  
59  very good  
(60, 9)
         exerany   hlthplan   smoke100     height      weight    wtdesire  \
count  60.000000  60.000000  60.000000  60.000000   60.000000   60.000000   
mean    0.750000   0.833333   0.516667  67.1833

# 3.1. Работа с числовыми данными
## 3.2.1. Пример
Прошкалируйте числовой признак в диапазон между двумя значениями.

In [ ]:
# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалировнный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

## 3.2.2. Пример
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [ ]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

Мы можем увидеть эффект стандартизации, обратившись к среднему
значению и стандартному отклонению результата нашего решения:

In [ ]:
print('Среднее: ', round(standardized.mean()))
print('Стандартное отклонение: ', standardized.std())

Среднее:  0
Стандартное отклонение:  1.0


## 3.2.3. Пример
Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']}) <br>
Необходимо масштабировать его числовые столбцы.

In [ ]:
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

## 3.3.2. Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования

In [9]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
scaler = MinMaxScaler()
dataframe[["sepal_length_cm"]] = scaler.fit_transform(dataframe[["sepal_length_cm"]])

sScaler = StandardScaler()
dataframe[["sepal_width_cm"]] = sScaler.fit_transform(dataframe[["sepal_width_cm"]])

print(dataframe.head(5))

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
